[tool.poetry]
name = "gpr-u-net-with-xai"
version = "0.1.0"
description = ""
authors = ["marcos <marcos.jacinto@geowellex.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numba = "^0.55.1"
shap = "^0.40.0"
tensorflow = "^2.8.0"
scikit-image = "^0.19.2"
segyio = "^1.9.9"

[tool.poetry.dev-dependencies]
black = "^22.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
